server:
    port: 9091
spring:
    application:
        name: payment-client

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            deafult-zone: http://localhost:8761/eureka
    instance:
        name: localhost