server:
    port: 8080
spring:
    application:
        name: GATEWAY-SERVICE
    cloud:
      gateway:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - Path=/user/**
          - id: PAYMENT-SERVICE
            uri: lb://PAYMENT-SERVICE
            predicates:
              - Path=/payment/**
          - id: ORDER-SERVICE
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/order/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      deafult-zone: http://localhost:8761/eureka
  instance:
    name: localhost
