server:
  port: 8081
spring:
  application:
      name: USER-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      deafult-zone: http://localhost:8761/eureka
  instance:
    name: localhost

